// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urlwskqsakvigidtutor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVybHdza3FzYWt2aWdpZHR1dG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjIyNjYsImV4cCI6MjA3MjE5ODI2Nn0.KZKKBqE9FJP6PWZV9gToLDX23znMrDCK05SZqaYz_cY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});